### ISSUE TITLE
Potential Mac Compatibility Issue

### ISSUE THREAD

**Issue by nxl5154** [DaveParillo/abs_humidity#14]
When using test-util as the Build Target, I can run the unit tests without any issues. However, switching to the test-calc Build Target cause the compilation to fail. Here are some of the errors, all seem to be inside json.hpp:
static constexpr std::size_t size() noexcept
NLOHMANN_JSON_HAS_HELPER(key_type);

Cameron can run this fine on his laptop, and we are both running up-to-date versions of the projects. I believe there is an issue of compatibility with Mac.

**Comment by DaveParillo** [comment]
What compiler version is the mac using? I can compile this using the default compiler in xcode:

    $ c++ --version
    Apple LLVM version 9.1.0 (clang-902.0.39.2)
    Target: x86_64-apple-darwin17.7.0

It's likely that the compiler in CodeBlocks for mac is not the same as in windows.
What version is it?

I did update the makefile to be consistent about include path, but this unrelated to your issue.

I'd be curious if you grab my makefile change if the makefile builds ok on your Mac.

**Comment by nxl5154** [comment]
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.7.0

My CodeBlocks compiler is clang with the flag '-std=c+=11'.

I will grab the new makefile and see what results I get. I haven't gone through my paths yet either, so I'll check that too.
